export const TITLES = ['นาย', 'นาง', 'น.ส.', 'อื่นๆ'];

export const DIAGNOSES = [
  'AML',
  'APL',
  'ALL',
  'MM',
  'HL',
  'NHL',
  'AA',
  'SC mobilization',
  'SC collection',
  'อื่นๆ'
];

export const REGIMENS = [
  '01. 7+3',
  '02. HiDAC',
  '03. IDAC',
  '04. FLAG-Ida',
  '05. FLAG',
  '06. MEC',
  '07. Azacitidine+Venetoclax',
  '08. ATRA+Ida induction',
  '09. ATRA+Ida+Cytarbine 1st conso',
  '10. ATRA+Ida+Cytarbine 3rd conso',
  '11. ATO + ATRA induction',
  '12. ATO + ATRA Consolidation',
  '13. AYA-ALL Phase I induction',
  '14. AYA-ALL Phase II conso wk 1-4',
  '15. AYA-ALL Phase II conso wk 5-8',
  '16. AYA-ALL Phase III - high dose MTX',
  '17. AYA-ALL Phase IV/II wk 5',
  '18. ALL Induction Phase I',
  '19. ALL Induction Phase II',
  '20. ALL Induction Phase III - high dose MTX',
  '21. ALL Induction Phase IV/II',
  '22. DCEP',
  '23. Escalated BEACOPDac',
  '24. Baseline BEACOPDac',
  '25. GDP',
  '26. R-DA-EPOCH for PMBCL',
  '27. DA-EPOCH for PMBCL',
  '28. EPOCH for T-Cell NHL',
  '29. R-DA-EPOCH for HIV related-NHL',
  '30. DA-EPOCH for HIV related-NHL',
  '31. R-ESHAP',
  '32. ESHAP',
  '33. R-ICE',
  '34. ICE',
  '35. R-DHAP',
  '36. DHAP',
  '37. R-FC For CLL',
  '38. FC For CLL',
  '39. R-CODOX – M(A)',
  '40. CODOX – M(A)',
  '41. R-IVAC(B)',
  '42. IVAC(B)',
  '43. AspaMetDex',
  '44. R-MTX-Ifosfamide',
  '45. MTX-Ifosfamide',
  '46. R-HD-MTX for PCNSL',
  '47. HD-MTX for PCNSL',
  '48. R-MTX-Cytarabine for PCNSL',
  '49. MTX-Cytarabine for PCNSL',
  '50. HD-MTX for CNS prophylaxis',
  '51. Obinituzumab-Chlorambucil For CLL',
  '52. R-Hyper CVAD (course 1,3,5,7)',
  '53. Hyper CVAD (course 1,3,5,7)',
  '54. R-Hyper CVAD (course 2,4,6,8)',
  '55. Hyper CVAD (course 2,4,6,8)',
  '56. ATG & cyclosporine ± Eltrombopag',
  '57. High Dose Cyclophosphamide',
  '58. SC collection',
  'อื่นๆ'
];
